### ISSUE TITLE
Error to simulate TTPs from the Atomic

### ISSUE THREAD

**Issue by johnk3r** [mitre/caldera#1927]
Hello, I'm starting to study Caldera and I have the following difficulty:

When I try to simulate an Atomic-related TTP, I am getting the following error message:

`import-module: The specified module 'PathToAtomicsFolder \ T1059.001 \ src \ SharpHound.ps1' has not been loaded because
no read module files found in any module directories.
...
(PathToAtomicsFo ... \ SharpHound.ps1: String) [Import-Module], FileNot
    FoundException
     + FullyQualifiedErrorId: Modules_ModuleNotFound, Microsoft.PowerShell.Commands.ImportModuleCommand`

I can see the imported TTP in the "/atomics" directory and the plugin was started with the server.
Where can I be wrong?

Congratulations for the project s2

**Comment by johnk3r** [comment]
Hello,

can someone help me or inform me where this is described in the documentation?

**Comment by wbooth** [comment]
Hi, the initial download may have been corrupted, there was an issue in one of the abilities that caused a circular dependency that has been fixed.

To reset atomic
Delete plugins/atomic/atomic-red-team directory
Delete plugins/atomic/data/abilities directory
Update atomic plugin to master 
Start up caldera

this should resolve your issue, please let me know if it does not

**Comment by johnk3r** [comment]
Thanks for the feedback.

So, I ended up upgrading to version 2.8.1. Unfortunately the problem remained.

I'm trying to simulate a T1059.001 technique, it has the following command:

`write-host "Importing and executing SharpHound.ps1 from PathToAtomicsFolder \ T1059.001 \ src" -ForegroundColor Cyan; import-module PathToAtomicsFolder \ T1059.001 \ src \ SharpHound.ps1; Invoke-BloodHound -OutputDirectory $ env: Temp; Start-Sleep 5`

Do I need to replace the "variable" PathToAtomicsFolder with something?

**Comment by wbooth** [comment]
Yes, you can replace the path to the payload

please note from our readme:

> When importing tests from Atomic Red Team, this plugin also catches $PathToAtomicsFolder usages pointing to an existing file. It then imports the files as payloads and fix path usages. Note other usages are not handled. If a path with $PathToAtomicsFolder points to an existing directory or an unexisting file, we will not process it any further and ingest it "as it is". Examples of such usages below: -- https://github.com/redcanaryco/atomic-red-team/blob/a956d4640f9186a7bd36d16a63f6d39433af5f1d/atomics/T1022/T1022.yaml#L99 -- https://github.com/redcanaryco/atomic-red-team/blob/ab0b391ac0d7b18f25cb17adb330309f92fa94e6/atomics/T1056/T1056.yaml#L24
